# Changes here will be overwritten by Copier
_commit: v7.3.0-24-g169e035
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-reason
project_description: Perform reasoning tasks and validate OWL consistency.
project_slug: reason
project_type: plugin
pypi: true

